[package]
name = "rucket_client"
version = "0.1.0"
authors = ["mattwparas <matthewparas2020@u.northwestern.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = "5.0.6"
rucket = { path = "./rucket" }
rucket_derive = { path = "./rucket_derive"}

[workspace]
members = [
    "rucket",
    "rucket_derive",
]